#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
  echo "这是 main 分支，开始打包..."
  npm run build || exit 1 # 如果打包失败，立即退出脚本

  # 检查是否有新的文件需要提交
  if ! git diff-index --quiet HEAD; then
    echo "打包成功，自动提交打包文件..."
    git add .
    git commit -m "Auto-build for main branch"
    git push origin main --no-verify
  else
    echo "打包后没有新的更改，跳过自动提交。"
  fi
else
  echo "当前分支不是 main，跳过打包。"
fi